name: Publish Docker
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: mdali-cf-cli
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: mdaali/sap_cf
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        registry: docker.pkg.github.com
        snapshot: true
        buildargs: MY_FIRST
        tags: mdaali/sap_cf
